const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_ERROR = "SIGNIN_ERROR";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_ERROR = "SIGNUP_ERROR";
const USER_LOADING = "USER_LOADING";
const USER_LOADED = "USER_LOADED";
const RESET_REQUEST = "RESET_REQUEST";

export {
  SIGNIN_SUCCESS,
  SIGNIN_ERROR,
  USER_LOADING,
  USER_LOADED,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  RESET_REQUEST
};
