const SIGNIN_SUCCESS = "SIGNIN_SUCCESS";
const SIGNIN_ERROR = "SIGNIN_ERROR";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_ERROR = "SIGNUP_ERROR";
const USER_LOADING = "USER_LOADING";
const USER_LOADED = "USER_LOADED";
const RESET_REQUEST = "RESET_REQUEST";
const RESET_PASS = "RESET_PASS";
const LANDING_DATA_SUCCESS = "LANDING_DATA_SUCCESS";
const LANDING_DATA_ERROR = "LANDING_DATA_ERROR";
const LOAD_MAIN_MAP_SUCCESS = "LOAD_MAIN_MAP_SUCCESS";
const LOAD_MAIN_MAP_ERROR = "LOAD_MAIN_MAP_ERROR";
const LOAD_MAIN_MAP_DATA_SUCCESS = "LOAD_MAIN_MAP_DATA_SUCCESS";
const LOAD_MAIN_MAP_DATA_ERROR = "LOAD_MAIN_MAP_DATA_ERROR";
const GOOGLE_LOGIN_SUCCESS = "GOOGLE_LOGIN_SUCCESS";
const GOOGLE_LOGIN_ERROR = "GOOGLE_LOGIN_ERROR";
const VERIFY_TOKEN_SUCCESS = "VERIFY_TOKEN_SUCCESS";
const VERIFY_TOKEN_ERROR = "VERIFY_TOKEN_ERROR";
const REQUEST_ERROR = "REQUEST_ERROR";
const LIPO_DATA_TABLE_SUCCESS = "LIPO_DATA_TABLE_SUCCESS";
const LIPO_DATA_TABLE_ERROR = "LIPO_DATA_TABLE_ERROR";

export {
  SIGNIN_SUCCESS,
  SIGNIN_ERROR,
  USER_LOADING,
  USER_LOADED,
  SIGNUP_SUCCESS,
  SIGNUP_ERROR,
  RESET_REQUEST,
  RESET_PASS,
  LANDING_DATA_SUCCESS,
  LANDING_DATA_ERROR,
  LOAD_MAIN_MAP_ERROR,
  LOAD_MAIN_MAP_SUCCESS,
  LOAD_MAIN_MAP_DATA_SUCCESS,
  LOAD_MAIN_MAP_DATA_ERROR,
  GOOGLE_LOGIN_SUCCESS,
  GOOGLE_LOGIN_ERROR,
  VERIFY_TOKEN_SUCCESS,
  VERIFY_TOKEN_ERROR,
  REQUEST_ERROR,
  LIPO_DATA_TABLE_SUCCESS,
  LIPO_DATA_TABLE_ERROR
};
